### ISSUE TITLE
Documentation not auto built

### ISSUE THREAD

**Issue by alexwaibel** [Kalafut-organization/elephant_vending_machine_frontend#8]
The GitHub pages hosted docs are currently outdated. It seems that as of right now we have to manually build them for each commit. I think we could use [this GitHub Action](https://github.com/marketplace/actions/deploy-to-github-pages) to remedy this.

**Comment by alexwaibel** [comment]
Documentation is now built automatically and deployed to branch `gh-pages`, however it seems to build an outdated version of the documentation

**Comment by brogers856** [comment]
Documentation now builds automatically and is up to date
